dFROM ubuntu
ENV TZ=Asia/Kolkata \
    DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install tzdata
RUN apt-get install -y checkinstall \
                    libreadline-gplv2-dev \
                    libncursesw5-dev \
                    libssl-dev \
                    libsqlite3-dev \
                    tk-dev \
                    libgdbm-dev \
                    libc6-dev \
                    libbz2-dev \
                    zlib1g-dev \
                    openssl \
                    libffi-dev \
                    python3-dev \
                    python3-setuptools \
                    wget


RUN apt-get install -y \
        software-properties-common
    RUN add-apt-repository ppa:deadsnakes/ppa
    RUN apt-get update && apt-get install -y \
        python3.7 \
        python3-pip
    RUN python3.7 -m pip install pip
    RUN apt-get update && apt-get install -y \
        python3-distutils \
        python3-setuptools


COPY ./ /app/

WORKDIR /app/

# RUN pip install --upgrade pip && \
#     pip install -r requirements.txt


#     pycontrol
# zkpython